env = "local"
base_url = "http://dzen.ru"
alias_length = 6
storage = "postgres"
secret_key = "qwerty"
[http_server]
address = "localhost:8083"
timeout = "4s"
idle_timeout = "60s"
[database]
driver       = "postgres"       # postgres | memory
dsn          = "postgres://postgres:mysecretpassword@localhost:5432/url4?sslmode=disable"
    [database.pool]               # сугубо для Postgres, но не мешает Memory-режиму
    max_open_conns = 10
    max_idle_conns = 5
    conn_lifetime  = "3m"